package main

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
	"time"
)

// The interop fixtures under tests/fixtures/company/interop/ are generated by
// the REAL Python code paths (slack_company_outbound.build_intent /
// build_delegation with a pinned clock). These tests consume those exact
// bytes through the real Go parse and claim paths, proving the
// cross-language record contract end to end without a cross-process harness.

func interopFixture(t *testing.T, name string) []byte {
	t.Helper()
	data, err := os.ReadFile(filepath.Join("..", "tests", "fixtures", "company", "interop", name))
	if err != nil {
		t.Fatalf("read interop fixture %s: %v", name, err)
	}
	return data
}

func TestInteropGoParsesPythonIntent(t *testing.T) {
	rec, err := companyParseIntent(interopFixture(t, "intent_python.json"))
	if err != nil {
		t.Fatalf("companyParseIntent on Python-authored intent: %v", err)
	}
	if rec.Nonce == "" || rec.Status == "" {
		t.Fatalf("parsed intent missing nonce/status: %+v", rec)
	}
}

func TestInteropGoClaimsPythonDelegation(t *testing.T) {
	raw := interopFixture(t, "delegation_python.json")
	rec, err := companyParseDelegation(raw)
	if err != nil {
		t.Fatalf("companyParseDelegation on Python-authored record: %v", err)
	}
	if rec.Status != companyDelegationPending {
		t.Fatalf("fixture must be pending, got %s", rec.Status)
	}

	// Lay the record out exactly where the Go claim path expects it: the
	// shared sanitizer-derived filename in the delegations dir.
	dir := t.TempDir()
	delegationsDir := filepath.Join(dir, "company-delegations")
	if err := os.MkdirAll(delegationsDir, 0o700); err != nil {
		t.Fatalf("mkdir: %v", err)
	}
	filename := companyDelegationFilename(rec.TeamID, rec.ChannelID, rec.TS)
	if err := os.WriteFile(filepath.Join(delegationsDir, filename), raw, 0o600); err != nil {
		t.Fatalf("write record: %v", err)
	}

	env := companyPeerEnv{
		delegationsDir: delegationsDir,
		intentsDir:     filepath.Join(dir, "company-delegation-intents"),
		locksDir:       filepath.Join(dir, "locks"),
		now:            func() time.Time { return time.Date(2026, 7, 17, 12, 5, 0, 0, time.UTC) },
	}
	m := delegationMatch{record: rec, filename: filename}
	const resultTS = "1700000000.000900"
	claimedAt := env.now().UTC().Format(time.RFC3339)
	claimedView := *rec
	claimedView.Status = companyDelegationClaimed
	claimedView.ResultTS = resultTS
	claimedView.ResultClaimedAt = claimedAt
	snap := env.computeSynthesisSnapshot(&claimedView, filename, claimedAt)
	if err := env.claimRecord(m, resultTS, claimedAt, snap); err != nil {
		t.Fatalf("claimRecord on Python-authored record: %v", err)
	}

	// Re-read through the Go parser: claimed, generation bumped, and the
	// Python-authored field set fully intact.
	data, err := os.ReadFile(filepath.Join(delegationsDir, filename))
	if err != nil {
		t.Fatalf("re-read: %v", err)
	}
	after, err := companyParseDelegation(data)
	if err != nil {
		t.Fatalf("re-parse after claim: %v", err)
	}
	if after.Status != companyDelegationClaimed || after.ResultTS != resultTS {
		t.Fatalf("claim did not apply: status=%s result_ts=%s", after.Status, after.ResultTS)
	}
	if after.Generation != rec.Generation+1 {
		t.Fatalf("generation = %d, want %d", after.Generation, rec.Generation+1)
	}
	if after.Nonce != rec.Nonce || after.RequesterSession != rec.RequesterSession {
		t.Fatalf("claim rewrite lost Python-authored fields: %+v", after)
	}

	// Replay of the same claim is idempotent.
	m2 := delegationMatch{record: after, filename: filename}
	if err := env.claimRecord(m2, resultTS, claimedAt, snap); err != nil {
		t.Fatalf("replayed claim not idempotent: %v", err)
	}
}

// bodySplitGoldenOrigin/Event are the pinned inputs for the cross-language
// body-split golden pair (m4): a bot-authored DM self-echo carrying a reconcile
// nonce, so the Python side can drive it through receipt_body AND
// _scan_receipt_for_nonce end to end.
var bodySplitGoldenOrigin = ReceiptOrigin{TeamID: "T0GOLDEN0", ChannelID: "C0GOLDEN0", TS: "1700000000.000123"}

const bodySplitGoldenEvent = `{"type":"message","subtype":"bot_message","bot_id":"B0GOLDEN0","app_id":"A0GOLDEN0","user":"U0GOLDEN0","channel":"C0GOLDEN0","ts":"1700000000.000123","text":"golden body-split payload","metadata":{"event_type":"gc_dm_reply","event_payload":{"v":1,"nonce":"gcs-golden-nonce"}}}`

// generateBodySplitGolden runs the REAL Admit path with a pinned clock into a temp
// store and returns the exact on-disk receipt bytes and body-sidecar bytes.
func generateBodySplitGolden(t *testing.T) (receiptBytes, bodyBytes []byte) {
	t.Helper()
	dir := filepath.Join(t.TempDir(), "chat-ingress")
	s, err := NewIngressReceiptStore(dir)
	if err != nil {
		t.Fatalf("NewIngressReceiptStore: %v", err)
	}
	pinned := time.Date(2026, 7, 19, 0, 0, 0, 0, time.UTC)
	r := &IngressReceipt{
		Origin:       bodySplitGoldenOrigin,
		EventID:      "Ev0GOLDEN0",
		APIAppID:     "A0GOLDEN0",
		ReceivedAt:   pinned,
		UpdatedAt:    pinned,
		ThreadRootTS: deriveHumanRootTS(decodeCompanyMessage(bodySplitGoldenOrigin, json.RawMessage(bodySplitGoldenEvent))),
		Event:        json.RawMessage(bodySplitGoldenEvent),
	}
	created, _, err := s.Admit(r)
	if err != nil || !created {
		t.Fatalf("golden Admit: created=%v err=%v", created, err)
	}
	receiptBytes, err = os.ReadFile(s.pathForID(r.ID))
	if err != nil {
		t.Fatalf("read golden receipt: %v", err)
	}
	bodyBytes, err = os.ReadFile(s.bodyPathForID(r.ID))
	if err != nil {
		t.Fatalf("read golden body: %v", err)
	}
	return receiptBytes, bodyBytes
}

// TestInteropBodySplitReceiptGolden pins the body-split receipt + sidecar wire
// shape (m4). The pair is generated by the real Go writer and committed under
// tests/fixtures/company/interop/; this asserts the writer still reproduces it
// byte-for-byte (a filename-suffix, digest, or field-spelling drift fails here),
// and the Python suite consumes the SAME committed bytes. Re-run with
// REGEN_GOLDEN=1 to refresh the fixtures after an intentional format change.
func TestInteropBodySplitReceiptGolden(t *testing.T) {
	gotReceipt, gotBody := generateBodySplitGolden(t)
	receiptFx := filepath.Join("..", "tests", "fixtures", "company", "interop", "receipt_body_split_go.json")
	bodyFx := filepath.Join("..", "tests", "fixtures", "company", "interop", "receipt_body_split_go.body.json")
	if os.Getenv("REGEN_GOLDEN") == "1" {
		if err := os.WriteFile(receiptFx, gotReceipt, 0o644); err != nil {
			t.Fatalf("write receipt fixture: %v", err)
		}
		if err := os.WriteFile(bodyFx, gotBody, 0o644); err != nil {
			t.Fatalf("write body fixture: %v", err)
		}
		t.Log("regenerated body-split golden fixtures")
	}
	wantReceipt := interopFixture(t, "receipt_body_split_go.json")
	wantBody := interopFixture(t, "receipt_body_split_go.body.json")
	if !bytes.Equal(gotReceipt, wantReceipt) {
		t.Errorf("body-split receipt drifted from the committed golden:\n got=%s\nwant=%s", gotReceipt, wantReceipt)
	}
	if !bytes.Equal(gotBody, wantBody) {
		t.Errorf("body-split sidecar drifted from the committed golden:\n got=%s\nwant=%s", gotBody, wantBody)
	}
}
