package main

import (
	"os"
	"path/filepath"
	"testing"
	"time"
)

// The interop fixtures under tests/fixtures/company/interop/ are generated by
// the REAL Python code paths (slack_company_outbound.build_intent /
// build_delegation with a pinned clock). These tests consume those exact
// bytes through the real Go parse and claim paths, proving the
// cross-language record contract end to end without a cross-process harness.

func interopFixture(t *testing.T, name string) []byte {
	t.Helper()
	data, err := os.ReadFile(filepath.Join("..", "tests", "fixtures", "company", "interop", name))
	if err != nil {
		t.Fatalf("read interop fixture %s: %v", name, err)
	}
	return data
}

func TestInteropGoParsesPythonIntent(t *testing.T) {
	rec, err := companyParseIntent(interopFixture(t, "intent_python.json"))
	if err != nil {
		t.Fatalf("companyParseIntent on Python-authored intent: %v", err)
	}
	if rec.Nonce == "" || rec.Status == "" {
		t.Fatalf("parsed intent missing nonce/status: %+v", rec)
	}
}

func TestInteropGoClaimsPythonDelegation(t *testing.T) {
	raw := interopFixture(t, "delegation_python.json")
	rec, err := companyParseDelegation(raw)
	if err != nil {
		t.Fatalf("companyParseDelegation on Python-authored record: %v", err)
	}
	if rec.Status != companyDelegationPending {
		t.Fatalf("fixture must be pending, got %s", rec.Status)
	}

	// Lay the record out exactly where the Go claim path expects it: the
	// shared sanitizer-derived filename in the delegations dir.
	dir := t.TempDir()
	delegationsDir := filepath.Join(dir, "company-delegations")
	if err := os.MkdirAll(delegationsDir, 0o700); err != nil {
		t.Fatalf("mkdir: %v", err)
	}
	filename := companyDelegationFilename(rec.TeamID, rec.ChannelID, rec.TS)
	if err := os.WriteFile(filepath.Join(delegationsDir, filename), raw, 0o600); err != nil {
		t.Fatalf("write record: %v", err)
	}

	env := companyPeerEnv{
		delegationsDir: delegationsDir,
		intentsDir:     filepath.Join(dir, "company-delegation-intents"),
		locksDir:       filepath.Join(dir, "locks"),
		now:            func() time.Time { return time.Date(2026, 7, 17, 12, 5, 0, 0, time.UTC) },
	}
	m := delegationMatch{record: rec, filename: filename}
	const resultTS = "1700000000.000900"
	if err := env.claimRecord(m, resultTS); err != nil {
		t.Fatalf("claimRecord on Python-authored record: %v", err)
	}

	// Re-read through the Go parser: claimed, generation bumped, and the
	// Python-authored field set fully intact.
	data, err := os.ReadFile(filepath.Join(delegationsDir, filename))
	if err != nil {
		t.Fatalf("re-read: %v", err)
	}
	after, err := companyParseDelegation(data)
	if err != nil {
		t.Fatalf("re-parse after claim: %v", err)
	}
	if after.Status != companyDelegationClaimed || after.ResultTS != resultTS {
		t.Fatalf("claim did not apply: status=%s result_ts=%s", after.Status, after.ResultTS)
	}
	if after.Generation != rec.Generation+1 {
		t.Fatalf("generation = %d, want %d", after.Generation, rec.Generation+1)
	}
	if after.Nonce != rec.Nonce || after.RequesterSession != rec.RequesterSession {
		t.Fatalf("claim rewrite lost Python-authored fields: %+v", after)
	}

	// Replay of the same claim is idempotent.
	m2 := delegationMatch{record: after, filename: filename}
	if err := env.claimRecord(m2, resultTS); err != nil {
		t.Fatalf("replayed claim not idempotent: %v", err)
	}
}
